disabled_rules: # rule identifiers turned on by default to exclude from running
  - identifier_name
  - shorthand_operator
  - nesting # Disable having more then 1 level nested type definitions.
  - function_parameter_count
  - redundant_string_enum_value
  - todo
  - cyclomatic_complexity
  - function_body_length
  - multiple_closures_with_trailing_closure # Should probably activate later on.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - MSACucumberTests
  - MSATests

force_cast:
  severity: warning

line_length:
  warning: 200
  error: 500
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
