name: APIClientTests
on:
  push:

  pull_request:

jobs:
  deploy_docs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish Jazzy Docs
        uses: steven0351/publish-jazzy-docs@v1
        with:
          personal_access_token: ${{ secrets.ACCESS_TOKEN }}

  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: xcodebuild clean test -project 'APIClient.xcodeproj' -scheme 'APIClient' -destination "platform=iOS Simulator,name=iPhone 11,OS=latest" -enableCodeCoverage 'YES'
      - name: Publish to Codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: 95348eee-42e2-4789-81c2-407909600e82
